version: 2
updates:
- package-ecosystem: npm
  directory: "/"
  schedule:
    interval: monthly
    time: "06:00"
    timezone: Australia/Canberra
  open-pull-requests-limit: 2
  target-branch: staging
