# https://github.com/FirebaseExtended/action-hosting-deploy#options

name: Deploy to Firebase Hosting Preview on PR
on:
  pull_request:
    types:
      - opened
      - reopened
      - synchronize
      - edited
    branches:
      - staging
    paths:
      - '.github/workflows/firebase-hosting-pull-request.yml'
      - 'package-lock.json'
      - 'public/**'
      - 'src/**'

jobs:
  build_and_preview:
    runs-on: ubuntu-latest
    environment: staging
    env:
      REACT_APP_BUILD_SHA1: '${{ github.sha }}'
      REACT_APP_BUILD_TAG: '${{ github.ref }}'
      REACT_APP_BUILD_BRANCH: '${{ github.head_ref }}'
      REACT_APP_BUILD_PULL_REQUESTS: '${{ github.event.pull_request.url }}'
      REACT_APP_BUILD_REPOSITORY_URL: 'https://github.com/${{ github.repository }}'
    steps:
      - uses: actions/checkout@v2

      - uses: actions/cache@v2
        with:
          path: ~/.npm
          key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-node-

      - name: Build app
        run: |
          npm ci
          npm run build

      - uses: FirebaseExtended/action-hosting-deploy@v0
        with:
          repoToken: '${{ secrets.GITHUB_TOKEN }}'
          firebaseServiceAccount: '${{ secrets.FIREBASE_SERVICE_ACCOUNT_CO_REALITY_MAP }}'
          projectId: co-reality-staging
          target: co-reality-staging
          expires: 14d
        env:
          FIREBASE_CLI_PREVIEWS: hostingchannels
